#!/usr/bin/env python

from optparse import OptionParser

import sys
import os
import Image
import ImageDraw

def redraw(im, scale):
    """Redraws image where each pixel now occupies scale x scale pixels
    """
    size = im.size
    new = Image.new("RGB", (size[0] * scale, size[1] * scale))
    imc = im.convert("RGB")
    draw = ImageDraw.Draw(new)

    for x in range(size[0]):
        for y in range(size[1]):
            px = imc.getpixel((x, y))
            draw.rectangle([x*scale, y*scale, 
                            (x*scale) + scale, (y*scale) + scale], fill=px)

    return new


parser = OptionParser(usage='%prog [options] src dest')
parser.add_option('-s', '--scale', dest='scale', type='int', default=10,
                  help='size of new blocks')

if __name__ == '__main__':
    (options, args) = parser.parse_args()
    if len(args) != 2:
        parser.print_help()
        raise SystemExit()

    if not os.path.isfile(args[0]) or not os.access(args[0], os.R_OK):
        sys.stderr.write("ERROR: don't have permission to open %s" % args[0])
        raise SystemExit()

    new = redraw(Image.open(args[0]), options.scale)
    new.save(args[1])
        
            
    
